databases:
  - name: hue-forestwatch-db
    databaseName: forestwatch
    user: forestwatch
    plan: free
    region: singapore

services:
  - type: web
    name: hue-forestwatch
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hue-forestwatch-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://hue-forestwatch.onrender.com
      - key: SADMIN_USERNAME
        value: sadmin
      - key: SADMIN_PASSWORD
        sync: false
      - key: ADMIN_API_BASE
        value: https://34tinhthanh.com/api
